import time

local_time = time.localtime()
print("localtime:")
print(f"tm_year : {local_time.tm_year}")
print(f"tm_mon  : {local_time.tm_mon}")
print(f"tm_mday : {local_time.tm_mday}")
print(f"tm_hour : {local_time.tm_hour}")
print(f"tm_min  : {local_time.tm_min}")
print(f"tm_sec  : {local_time.tm_sec}")
print(f"tm_wday : {local_time.tm_wday}")
print(f"tm_yday : {local_time.tm_yday}")
print(f"tm_isdst: {local_time.tm_isdst}")

gmt_time = time.gmtime()
print("\ngmtime:")
print(f"tm_year : {gmt_time.tm_year}")
print(f"tm_mon  : {gmt_time.tm_mon}")
print(f"tm_mday : {gmt_time.tm_mday}")
print(f"tm_hour : {gmt_time.tm_hour}")
print(f"tm_min  : {gmt_time.tm_min}")
print(f"tm_sec  : {gmt_time.tm_sec}")
print(f"tm_wday : {gmt_time.tm_wday}")
print(f"tm_yday : {gmt_time.tm_yday}")
print(f"tm_isdst: {gmt_time.tm_isdst}")